language: rust
rust:
  - stable
  - beta
  - nightly
  - 1.13.0
  - 1.14.0
  - 1.15.0
  - 1.16.0
matrix:
  allow_failures:
    - rust: nightly
addons:
  apt:
    sources:
      - george-edison55-precise-backports
    packages:
      - cmake
      - cmake-data
