[package]
name = "git-dit"
version = "0.1.0"
authors = ["Matthias Beyer <mail@beyermatthias.de>",
           "Julian Ganz <neither@nut.email>"]

[workspace]
members = [
    "lib"
]

[dependencies]
log = "0.3"
git2 = "0.6"
error-chain = "0.10"

[dependencies.clap]
version = "2.23"
default-features = false
features = [ "suggestions", "color", "yaml" ]

[dependencies.libgitdit]
path = "./lib/"

